#! /bin/sh

hyprctl keyword windowrule "workspace 8 silent,Caprine" && hyprctl dispatch exec "$HOME/.local/bin/open-wl caprine"
sleep 2
hyprctl keyword windowrule "workspace 7 silent,discord" && hyprctl dispatch exec discord-canary

sleep 15

hyprctl keyword windowrule "unset,discord"
hyprctl keyword windowrule "unset,Caprine"
#hyprctl reload
