#! /bin/bash

#Switches wallpaper based on charging status
wptoggle () {
    if [[ "${1:21}" == "discharging" && "$1" != "$laststate" ]]; then
      hyprctl dispatch exec "swaybg -m fill -i ~/Pictures/GoW/GOW1.png" && eww -c ~/.config/hypr/bar/ reload & sleep 5 && pkill mpvpaper
      eww -c ~/.config/hypr/bar/ reload
    elif [[ "${1:21}" == "fully-charged" && "$1" != "$laststate" ]]; then
      :
    elif [[ "$1" != "$laststate" ]]; then
      hyprctl dispatch exec "mpvpaper -spf -o '--loop=120 --reset-on-next-file=loop --loop-playlist --shuffle --panscan=1' eDP-1 $HOME/Pictures/GoW/Clips/" && eww -c ~/.config/hypr/bar/ reload & sleep 5 && pkill swaybg
      
    fi
    
    export laststate=$1
  }

upower -d | grep --line-buffered state | wptoggle -
sleep 5
upower --monitor-detail  "upower -e | grep BAT" | grep --line-buffered state | while read -r state; do
wptoggle "$state"
done
