#! /bin/bash
stills="$HOME/Pictures/GoW/"
videos="$HOME/Pictures/GoW/Clips/"

#Switches wallpaper based on charging status
wptoggle () {
    if [[ "${1:21}" == "discharging" && "$1" != "$laststate" ]]; then
      hyprctl dispatch exec "swaybg -m fill -i $(find $stills -maxdepth 1 -type f | shuf -n 1)" && eww -c ~/.config/hypr/bar/ reload & sleep 5 && pkill mpvpaper
    elif [[ "${1:21}" == "fully-charged" && "$1" != "$laststate" ]]; then
      :
    elif [[ "$1" != "$laststate" ]]; then
      hyprctl dispatch exec "mpvpaper -spf -o '--loop=120 --reset-on-next-file=loop --loop-playlist --shuffle --panscan=1' eDP-1 $videos" && eww -c ~/.config/hypr/bar/ reload & sleep 5 && pkill swaybg
    fi
    
    export laststate=$1
  }

upower -d | grep --line-buffered state | wptoggle -
sleep 5
upower --monitor-detail  "upower -e | grep BAT" | grep --line-buffered state | while read -r state; do
wptoggle "$state"
done
