#! /bin/bash
monitors=/tmp/hypr/monitors_temp
hyprctl monitors > $monitors

activemonitor=$(grep -B 6 "active: yes" "$monitors" | awk 'NR==1 {print $2}')
passivemonitor=$(grep  -B 2 "($1)" "$monitors" | awk 'NR==1 {print $2}')
activews=$(grep -A 2 "$activemonitor" "$monitors" | awk 'NR==3 {print $1}' RS='(' FS=')')
passivews=$(grep -A 2 "$passivemonitor" "$monitors" | awk 'NR==3 {print $1}' RS='(' FS=')')

[[ $1 -eq $passivews ]] && [[ $activemonitor != "$passivemonitor" ]] && (hyprctl dispatch moveworkspacetomonitor "$activews $passivemonitor")
hyprctl dispatch moveworkspacetomonitor "$1 $activemonitor" && hyprctl dispatch workspace "$1"
[[ $1 -eq $passivews ]] && [[ $activemonitor != "$passivemonitor" ]] && (hyprctl dispatch focusmonitor $passivemonitor && hyprctl dispatch workspace $activews && hyprctl dispatch focusmonitor $activemonitor)

exit 0
