#!/bin/sh

status=$(nmcli g | grep -oE "disconnected")
essid=$(nmcli -t -f active,ssid dev wifi | grep '^yes' | cut -d: -f2)

if [ $status ] ; then
    icon="睊"
    text=""
    col="#575268"

else
    icon=""
    text="${essid}"
    col="#a1bdce"
fi



if [[ "$1" == "--COL" ]]; then
    echo $col	
elif [[ "$1" == "--ESSID" ]]; then
	echo $text
elif [[ "$1" == "--ICON" ]]; then
	echo $icon
fi

